name: "Copilot Setup Steps"

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Setup Python (for uvx/MCP servers)
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uvx
        run: pip install uv

      - name: Pre-cache MCP servers
        run: |
          # Cache uvx-based servers (fetch, serena)
          uvx mcp-server-fetch --help || true
          uvx --from "git+https://github.com/oraios/serena" serena --help || true

          # Cache npx-based servers (playwright, chrome-devtools, sequentialthinking, ai-agent-guidelines)
          npx -y @playwright/mcp@latest --help || true
          npx -y chrome-devtools-mcp@latest --help || true
          npx -y @modelcontextprotocol/server-sequential-thinking@latest --help || true
          npx -y mcp-ai-agent-guidelines@latest --help || true

          # Note: HTTP servers (deepwiki, context7) require no pre-caching
