name: 🐛 Bug Report
description: Report a bug to help us improve the project
title: "🐛 [BUG] - [Brief description]"
labels: ["bug", "needs-triage"]
projects: []
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report Form
        
        Thank you for taking the time to report a bug! Please fill out this form to help us understand and reproduce the issue.

  - type: dropdown
    id: bug_type
    attributes:
      label: 🏷️ Bug Type
      description: "What type of bug are you reporting?"
      options:
        - 🔧 Installation/Setup Issue
        - ⚡ Performance Problem
        - 💥 Application Crash
        - 🔄 Incorrect Behavior
        - 📱 UI/UX Issue
        - 🔌 Integration/Compatibility Issue
        - 📚 Documentation Error
        - 🛡️ Security Concern
        - 🌐 Network/Connectivity Issue
        - 📦 Dependency Issue
        - 🔍 Other (please specify)
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: 🚨 Severity Level
      description: "How severely does this bug impact your work?"
      options:
        - 🔴 Critical - Blocking all work
        - 🟠 High - Significantly impacts functionality
        - 🟡 Medium - Moderate impact, workaround exists
        - 🟢 Low - Minor issue, cosmetic or edge case
        - 🔵 Enhancement - Improvement suggestion
    validations:
      required: true

  - type: textarea
    id: bug_description
    attributes:
      label: 📝 Bug Description
      description: "A clear and concise description of what the bug is"
      placeholder: |
        Describe what happened and what you expected to happen.
        
        Example: "When I run the command 'npm run build', it fails with a TypeScript error, but I expected it to compile successfully."
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: 🔄 Steps to Reproduce
      description: "Detailed steps to reproduce the behavior"
      placeholder: |
        1. Go to '...'
        2. Run command '...'
        3. Click on '...'
        4. See error
        
        Please be as specific as possible - include exact commands, file paths, and inputs.
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: ✅ Expected Behavior
      description: "What you expected to happen"
      placeholder: "Describe what should have happened instead of the bug."
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: ❌ Actual Behavior  
      description: "What actually happened"
      placeholder: "Describe what actually happened, including any error messages."
    validations:
      required: true

  - type: dropdown
    id: operating_system
    attributes:
      label: 💻 Operating System
      description: "Which operating system are you using?"
      options:
        - 🍎 macOS (Intel)
        - 🍎 macOS (Apple Silicon)
        - 🐧 Linux (Ubuntu/Debian)
        - 🐧 Linux (RHEL/CentOS/Fedora)
        - 🐧 Linux (Other)
        - 🪟 Windows 10
        - 🪟 Windows 11
        - 🐳 Docker Container
        - ☁️ GitHub Codespaces
        - ☁️ Other Cloud Environment
    validations:
      required: true

  - type: dropdown
    id: node_version
    attributes:
      label: 🟢 Node.js Version
      description: "Which version of Node.js are you using?"
      options:
        - 18.x (LTS)
        - 20.x (LTS) 
        - 22.x (Current)
        - 23.x (Current)
        - Other (specify in additional context)
        - Unknown
    validations:
      required: true

  - type: input
    id: package_version
    attributes:
      label: 📦 Package Version
      description: "Which version of mcp-ai-agent-guidelines are you using?"
      placeholder: "e.g., 0.6.0, latest, or commit hash"
    validations:
      required: true

  - type: dropdown
    id: installation_method
    attributes:
      label: 📥 Installation Method
      description: "How did you install the package?"
      options:
        - 📦 NPM (npm install)
        - 🧶 Yarn
        - 📦 NPX (npx command)
        - 🐳 Docker
        - 📁 Git clone
        - 🏗️ Built from source
        - 📱 VS Code Extension/MCP
        - Other (specify below)
    validations:
      required: false

  - type: textarea
    id: error_logs
    attributes:
      label: 📋 Error Messages/Logs
      description: "Paste any relevant error messages or logs"
      placeholder: |
        Paste complete error messages here. Include:
        - Command line output
        - Browser console errors
        - Application logs
        - Stack traces
        
        Use triple backticks (```) to format code blocks.
      render: text
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: 🖼️ Screenshots/Visual Evidence
      description: "Add screenshots or screen recordings if applicable"
      placeholder: |
        Drag and drop images here or use:
        - GitHub's image paste functionality
        - Links to screenshots (imgur, etc.)
        - Describe visual issues if you can't provide images
    validations:
      required: false

  - type: checkboxes
    id: troubleshooting_checklist
    attributes:
      label: ✅ Troubleshooting Checklist
      description: "Please confirm you've tried these basic troubleshooting steps"
      options:
        - label: "I have updated to the latest version"
          required: false
        - label: "I have cleared npm/yarn cache"
          required: false
        - label: "I have tried reinstalling dependencies (npm ci)"
          required: false
        - label: "I have checked the documentation and README"
          required: false
        - label: "I have searched existing issues for duplicates"
          required: true
        - label: "I can reproduce this issue consistently"
          required: false

  - type: textarea
    id: workaround
    attributes:
      label: 🔧 Workaround (if any)
      description: "If you found a temporary workaround, please share it"
      placeholder: |
        Describe any workarounds you've discovered that might help others
        or provide clues for fixing the issue.
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: 📎 Additional Context
      description: "Any other context, configuration details, or information that might be relevant"
      placeholder: |
        Add any other context about the problem here:
        - Special configuration settings
        - Environment variables
        - Network setup
        - Related tools or dependencies
        - Timeline (when did this start happening?)
    validations:
      required: false

  - type: checkboxes
    id: submission_checklist
    attributes:
      label: 📋 Final Checklist
      description: "Before submitting, please confirm:"
      options:
        - label: "I have provided clear steps to reproduce the issue"
          required: true
        - label: "I have included relevant error messages and logs"
          required: false
        - label: "I have checked that this isn't a duplicate of an existing issue"
          required: true
        - label: "I understand this is a public repository and my submission is visible to everyone"
          required: true