import { existsSync, mkdtempSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import type { GraphAnalysis } from "../../contracts/graph-types.js";
import {
	DocumentationIntegrationEngine,
	type GraphVisualizationData,
} from "../../presentation/documentation-integration.js";

describe("presentation/documentation-integration", () => {
	it("generates data-driven documentation artifacts without internal wave language", async () => {
		const outputDirectory = mkdtempSync(join(tmpdir(), "docs-integration-"));
		const engine = new DocumentationIntegrationEngine({
			outputDirectory,
			includeVisualizations: true,
			includePerformanceData: true,
		});

		const result = await engine.generateArchitectureDocumentation(
			{
				agents: [
					{ id: "agent-1", name: "Planner" },
					{ id: "agent-2", name: "Reviewer" },
				],
				skills: [
					{
						id: "debug-root-cause",
						domain: "debug",
						dependencies: ["debug-assistant"],
					},
					{
						id: "qual-review",
						domain: "qual",
						dependencies: [],
					},
				],
				routes: [{ from: "agent-1", to: "agent-2" }],
				metrics: [],
			} as unknown as GraphVisualizationData,
			{
				agentTopology: { edgeCount: 1 },
				bottlenecks: [{ node: "agent-1", score: 0.75, type: "agent" }],
				recommendations: ["Add redundancy"],
			} as unknown as GraphAnalysis,
			[
				{
					skillId: "debug-root-cause",
					description: "Diagnose failures",
					domain: "debug",
					dependencies: ["debug-assistant"],
					usageExamples: ["Find root cause"],
					interactions: [
						{
							withSkill: "qual-review",
							frequency: 7,
							successRate: 0.91,
						},
					],
					performanceProfile: {
						averageLatency: 42,
						successRate: 0.97,
						utilizationRate: 0.65,
					},
				},
				{
					skillId: "qual-review",
					description: "Review the result",
					domain: "qual",
					dependencies: [],
					usageExamples: ["Review output"],
					interactions: [
						{
							withSkill: "debug-root-cause",
							frequency: 7,
							successRate: 0.91,
						},
					],
				},
			],
		);

		expect(result).toBe(outputDirectory);
		expect(existsSync(join(outputDirectory, "ARCHITECTURE.md"))).toBe(true);
		expect(
			existsSync(join(outputDirectory, "visuals", "agent-topology.svg")),
		).toBe(true);

		const architectureDoc = readFileSync(
			join(outputDirectory, "ARCHITECTURE.md"),
			"utf8",
		);
		const interactionDoc = readFileSync(
			join(outputDirectory, "SKILL_INTERACTIONS.md"),
			"utf8",
		);
		const indexDoc = readFileSync(join(outputDirectory, "README.md"), "utf8");
		const topologySvg = readFileSync(
			join(outputDirectory, "visuals", "agent-topology.svg"),
			"utf8",
		);

		expect(architectureDoc).toContain(
			"2 agents, 2 skills, and 1 routing connections",
		);
		expect(architectureDoc).toContain("Planner");
		expect(architectureDoc).toContain("debug: 1 skills");
		expect(architectureDoc).not.toContain("Wave");
		expect(interactionDoc).toContain("debug-root-cause");
		expect(interactionDoc).toContain("qual-review");
		expect(interactionDoc).not.toContain("Wave");
		expect(indexDoc).toContain("Generated on");
		expect(indexDoc).not.toContain("Wave");
		expect(topologySvg).toContain("Planner");
	});

	it("creates dynamic interaction and performance maps from the supplied data", async () => {
		const outputDirectory = mkdtempSync(join(tmpdir(), "docs-visuals-"));
		const engine = new DocumentationIntegrationEngine({
			outputDirectory,
			includePerformanceData: true,
		});

		await engine.generateSkillInteractionMaps(
			[
				{
					skillId: "adapt",
					description: "Adaptive routing",
					domain: "adapt",
					dependencies: ["evaluate"],
					usageExamples: [],
					interactions: [
						{ withSkill: "evaluate", frequency: 4, successRate: 0.8 },
					],
				},
				{
					skillId: "evaluate",
					description: "Benchmark quality",
					domain: "eval",
					dependencies: [],
					usageExamples: [],
					interactions: [
						{ withSkill: "adapt", frequency: 4, successRate: 0.8 },
					],
				},
			],
			[
				{
					entityId: "adapt",
					metricName: "latency",
					name: "latency",
					value: 84,
					unit: "ms",
					timestamp: Date.now(),
				},
			],
		);

		const interactionSvg = readFileSync(
			join(outputDirectory, "visuals", "skill-interaction-network.svg"),
			"utf8",
		);
		const performanceSvg = readFileSync(
			join(outputDirectory, "visuals", "skill-performance-map.svg"),
			"utf8",
		);

		expect(interactionSvg).toContain("adapt: 4 recorded interactions");
		expect(interactionSvg).not.toContain("Generated by Wave");
		expect(performanceSvg).toContain("adapt: avg 84.0 ms across 1 metrics");
		expect(performanceSvg).not.toContain("Generated by Wave");
	});
});
