import { existsSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import type { GraphAnalysis } from "../../contracts/graph-types.js";
import {
	DocumentationIntegrationEngine,
	type GraphVisualizationData,
} from "../../presentation/documentation-integration.js";

describe("presentation/documentation-integration", () => {
	const tempDirs: string[] = [];

	afterEach(() => {
		for (const dir of tempDirs.splice(0)) {
			rmSync(dir, { recursive: true, force: true });
		}
	});

	function makeTempDir(prefix: string): string {
		const dir = mkdtempSync(join(tmpdir(), prefix));
		tempDirs.push(dir);
		return dir;
	}

	it("generates data-driven documentation artifacts without internal wave language", async () => {
		const outputDirectory = makeTempDir("docs-integration-");
		const engine = new DocumentationIntegrationEngine({
			outputDirectory,
			includeVisualizations: true,
			includePerformanceData: true,
		});

		const result = await engine.generateArchitectureDocumentation(
			{
				agents: [
					{ id: "agent-1", name: "Planner" },
					{ id: "agent-2", name: "Reviewer" },
				],
				skills: [
					{
						id: "debug-root-cause",
						domain: "debug",
						dependencies: ["debug-assistant"],
					},
					{
						id: "qual-review",
						domain: "qual",
						dependencies: [],
					},
				],
				routes: [{ from: "agent-1", to: "agent-2" }],
				metrics: [],
			} as unknown as GraphVisualizationData,
			{
				agentTopology: { edgeCount: 1 },
				bottlenecks: [{ node: "agent-1", score: 0.75, type: "agent" }],
				recommendations: ["Add redundancy"],
			} as unknown as GraphAnalysis,
			[
				{
					skillId: "debug-root-cause",
					description: "Diagnose failures",
					domain: "debug",
					dependencies: ["debug-assistant"],
					usageExamples: ["Find root cause"],
					interactions: [
						{
							withSkill: "qual-review",
							frequency: 7,
							successRate: 0.91,
						},
					],
					performanceProfile: {
						averageLatency: 42,
						successRate: 0.97,
						utilizationRate: 0.65,
					},
				},
				{
					skillId: "qual-review",
					description: "Review the result",
					domain: "qual",
					dependencies: [],
					usageExamples: ["Review output"],
					interactions: [
						{
							withSkill: "debug-root-cause",
							frequency: 7,
							successRate: 0.91,
						},
					],
				},
			],
		);

		expect(result).toBe(outputDirectory);
		expect(existsSync(join(outputDirectory, "ARCHITECTURE.md"))).toBe(true);
		expect(
			existsSync(join(outputDirectory, "visuals", "agent-topology.svg")),
		).toBe(true);

		const architectureDoc = readFileSync(
			join(outputDirectory, "ARCHITECTURE.md"),
			"utf8",
		);
		const interactionDoc = readFileSync(
			join(outputDirectory, "SKILL_INTERACTIONS.md"),
			"utf8",
		);
		const indexDoc = readFileSync(join(outputDirectory, "README.md"), "utf8");
		const topologySvg = readFileSync(
			join(outputDirectory, "visuals", "agent-topology.svg"),
			"utf8",
		);

		expect(architectureDoc).toContain(
			"2 agents, 2 skills, and 1 routing connections",
		);
		expect(architectureDoc).toContain("Planner");
		expect(architectureDoc).toContain("debug: 1 skills");
		expect(architectureDoc).not.toContain("Wave");
		expect(interactionDoc).toContain("debug-root-cause");
		expect(interactionDoc).toContain("qual-review");
		expect(interactionDoc).not.toContain("Wave");
		expect(indexDoc).toContain("Generated on");
		expect(indexDoc).not.toContain("Wave");
		expect(topologySvg).toContain("Planner");
	});

	it("creates dynamic interaction and performance maps from the supplied data", async () => {
		const outputDirectory = makeTempDir("docs-visuals-");
		const engine = new DocumentationIntegrationEngine({
			outputDirectory,
			includePerformanceData: true,
		});

		await engine.generateSkillInteractionMaps(
			[
				{
					skillId: "adapt",
					description: "Adaptive routing",
					domain: "adapt",
					dependencies: ["evaluate"],
					usageExamples: [],
					interactions: [
						{ withSkill: "evaluate", frequency: 4, successRate: 0.8 },
					],
				},
				{
					skillId: "evaluate",
					description: "Benchmark quality",
					domain: "eval",
					dependencies: [],
					usageExamples: [],
					interactions: [
						{ withSkill: "adapt", frequency: 4, successRate: 0.8 },
					],
				},
			],
			[
				{
					entityId: "adapt",
					metricName: "latency",
					name: "latency",
					value: 84,
					unit: "ms",
					timestamp: Date.now(),
				},
			],
		);

		const interactionSvg = readFileSync(
			join(outputDirectory, "visuals", "skill-interaction-network.svg"),
			"utf8",
		);
		const performanceSvg = readFileSync(
			join(outputDirectory, "visuals", "skill-performance-map.svg"),
			"utf8",
		);

		expect(interactionSvg).toContain("adapt: 4 recorded interactions");
		expect(interactionSvg).not.toContain("Generated by Wave");
		expect(performanceSvg).toContain("adapt: avg 84.0 ms across 1 metrics");
		expect(performanceSvg).not.toContain("Generated by Wave");
	});

	it("generates API documentation directory with per-skill and overview files", async () => {
		const outputDirectory = makeTempDir("docs-api-");
		const engine = new DocumentationIntegrationEngine({ outputDirectory });

		const skillDocs = [
			{
				skillId: "debug-assistant",
				description: "Helps debug issues",
				domain: "debug",
				dependencies: [],
				usageExamples: ["Find bugs"],
				interactions: [],
				performanceProfile: {
					averageLatency: 50,
					successRate: 0.95,
					utilizationRate: 0.7,
				},
			},
			{
				skillId: "qual-review",
				description: "Review quality",
				domain: "qual",
				dependencies: ["debug-assistant"],
				usageExamples: [],
				interactions: [
					{ withSkill: "debug-assistant", frequency: 3, successRate: 0.9 },
				],
			},
		];

		const apiDir = await engine.generateApiDocumentation(skillDocs);
		expect(existsSync(join(apiDir, "debug-assistant.md"))).toBe(true);
		expect(existsSync(join(apiDir, "qual-review.md"))).toBe(true);
		expect(existsSync(join(apiDir, "README.md"))).toBe(true);

		const overview = readFileSync(join(apiDir, "README.md"), "utf8");
		expect(overview).toContain("debug-assistant");
		expect(overview).toContain("qual-review");
	});

	it("updates documentation for changed skills only", async () => {
		const outputDirectory = makeTempDir("docs-update-");
		const engine = new DocumentationIntegrationEngine({ outputDirectory });

		const skillDocs = [
			{
				skillId: "skill-a",
				description: "Skill A",
				domain: "debug",
				dependencies: [],
				usageExamples: [],
				interactions: [],
			},
			{
				skillId: "skill-b",
				description: "Skill B",
				domain: "qual",
				dependencies: [],
				usageExamples: [],
				interactions: [],
			},
		];

		// Generate initial API docs first
		await engine.generateApiDocumentation(skillDocs);

		// Update only one skill
		await engine.updateDocumentationFromSkillChanges(["skill-a"], skillDocs);

		const updatedDoc = readFileSync(
			join(outputDirectory, "api", "skill-a.md"),
			"utf8",
		);
		expect(updatedDoc).toContain("skill-a");
	});

	it("updateDocumentationFromSkillChanges skips skills not found in skillDocs", async () => {
		const outputDirectory = makeTempDir("docs-skip-");
		const engine = new DocumentationIntegrationEngine({ outputDirectory });

		const skillDocs = [
			{
				skillId: "skill-existing",
				description: "Existing skill",
				domain: "debug",
				dependencies: [],
				usageExamples: [],
				interactions: [],
			},
		];

		// Generate initial API docs
		await engine.generateApiDocumentation(skillDocs);

		// Update with a skill that doesn't exist in skillDocs — should not throw
		await expect(
			engine.updateDocumentationFromSkillChanges(
				["skill-nonexistent"],
				skillDocs,
			),
		).resolves.toBeUndefined();
	});

	it("generateArchitectureDocumentation covers default-config else-paths and same-domain skills", async () => {
		const outputDirectory = makeTempDir("docs-defaults-");
		// Default config: includeVisualizations=false, includePerformanceData=false, includeCodeExamples=true
		const engine = new DocumentationIntegrationEngine({ outputDirectory });

		await engine.generateArchitectureDocumentation(
			{
				// No id/name/domain/dependencies on first skill → triggers ?? fallbacks in createArchitectureDocument
				agents: null,
				skills: [
					{ id: null, name: null, domain: null, dependencies: null },
					{ id: "skill-x", domain: "debug", dependencies: [] },
				],
				routes: null,
			} as unknown as GraphVisualizationData,
			{
				agentTopology: null,
				// empty bottlenecks and recommendations → triggers "no data" else-branches
				bottlenecks: [],
				recommendations: [],
			} as unknown as GraphAnalysis,
			[
				// Two skills in the same domain → second skips domainGroups initialisation (line 340 if[1])
				// Empty usageExamples → skips code-examples block (line 374 if[1])
				{
					skillId: "skill-a",
					description: "A",
					domain: "debug",
					dependencies: [],
					usageExamples: [],
					interactions: [],
				},
				{
					skillId: "skill-b",
					description: "B",
					domain: "debug",
					dependencies: [],
					usageExamples: [],
					interactions: [],
				},
			],
		);

		const archDoc = readFileSync(
			join(outputDirectory, "ARCHITECTURE.md"),
			"utf8",
		);
		// No bottleneck/recommendation data → else-branch text present
		expect(archDoc).toContain("No bottlenecks were supplied");
		expect(archDoc).toContain("No runtime recommendations were supplied");
		// No visualisation section since includeVisualizations=false
		expect(archDoc).not.toContain("Generated Visualizations");
	});

	it("generateSkillInteractionMaps covers no-metrics path and edge-case recommendation branches", async () => {
		const outputDirectory = makeTempDir("docs-maps-edge-");
		const engine = new DocumentationIntegrationEngine({
			outputDirectory,
			includePerformanceData: true,
		});

		// Call 1: only isolated skills → no high-traffic pair (line 768 if[1] skip-path)
		await engine.generateSkillInteractionMaps([
			{
				skillId: "iso-a",
				description: "Isolated",
				domain: "debug",
				dependencies: [],
				usageExamples: [],
				interactions: [],
			},
		]);

		// No metrics argument → skips performance overlay map (line 199 if[1])
		expect(
			existsSync(join(outputDirectory, "visuals", "skill-performance-map.svg")),
		).toBe(false);
		expect(
			existsSync(
				join(outputDirectory, "visuals", "skill-interaction-network.svg"),
			),
		).toBe(true);

		// Call 2: rich data — low-success pair, isolated skill, and skill with ≥5 interactions
		await engine.generateSkillInteractionMaps(
			[
				// Isolated skill: no deps + no interactions → line 780 if[0]
				{
					skillId: "isolated",
					description: "Isolated",
					domain: "debug",
					dependencies: [],
					usageExamples: [],
					interactions: [],
				},
				// Pair with low success rate < 0.8 → line 774 if[0]
				{
					skillId: "low-success",
					description: "Low success",
					domain: "qual",
					dependencies: [],
					usageExamples: [],
					interactions: [
						{ withSkill: "high-interact", frequency: 5, successRate: 0.5 },
					],
				},
				// Skill with ≥5 interactions → line 789 if[0]
				{
					skillId: "high-interact",
					description: "Many interactions",
					domain: "qual",
					dependencies: [],
					usageExamples: [],
					interactions: [
						{ withSkill: "low-success", frequency: 5, successRate: 0.5 },
						{ withSkill: "a", frequency: 1, successRate: 0.9 },
						{ withSkill: "b", frequency: 1, successRate: 0.9 },
						{ withSkill: "c", frequency: 1, successRate: 0.9 },
						{ withSkill: "d", frequency: 1, successRate: 0.9 },
					],
				},
			],
			[
				{
					entityId: "high-interact",
					metricName: "latency",
					name: "latency",
					value: 100,
					unit: "ms",
					timestamp: Date.now(),
				},
			],
		);

		const networkSvg = readFileSync(
			join(outputDirectory, "visuals", "skill-interaction-network.svg"),
			"utf8",
		);
		expect(networkSvg).toContain("high-interact");
	});

	it("generateApiDocumentation includes performance profile and code examples when configs are enabled", async () => {
		const outputDirectory = makeTempDir("docs-api-full-");
		const engine = new DocumentationIntegrationEngine({
			outputDirectory,
			includePerformanceData: true,
			includeCodeExamples: true,
		});

		await engine.generateApiDocumentation([
			{
				skillId: "full-skill",
				description: "Full coverage skill",
				domain: "debug",
				dependencies: [],
				usageExamples: ["const x = doSomething();"],
				interactions: [],
				performanceProfile: {
					averageLatency: 30,
					successRate: 0.99,
					utilizationRate: 0.5,
				},
			},
			{
				// No performanceProfile → skips performance block (binary-expr[1] when B is falsy)
				skillId: "no-profile",
				description: "No profile",
				domain: "debug",
				dependencies: [],
				usageExamples: [],
				interactions: [],
			},
		]);

		const fullDoc = readFileSync(
			join(outputDirectory, "api", "full-skill.md"),
			"utf8",
		);
		expect(fullDoc).toContain("Performance Profile");
		expect(fullDoc).toContain("Usage Examples");
		expect(fullDoc).toContain("30ms");
	});

	it("generateArchitectureDocumentation with null graphData fields covers defensive-branch fallbacks", async () => {
		const outputDirectory = makeTempDir("docs-null-");
		const engine = new DocumentationIntegrationEngine({ outputDirectory });

		await engine.generateArchitectureDocumentation(
			{
				// null agents/skills/routes → Array.isArray() returns false → else-branch (cond-expr[1])
				agents: null,
				skills: [],
				routes: null,
			} as unknown as GraphVisualizationData,
			{
				agentTopology: null,
				bottlenecks: null,
				recommendations: null,
			} as unknown as GraphAnalysis,
			[],
		);

		expect(existsSync(join(outputDirectory, "ARCHITECTURE.md"))).toBe(true);
	});

	it("generateArchitectureDocumentation renders long interaction sections and visualization fallbacks", async () => {
		const outputDirectory = makeTempDir("docs-visual-fallbacks-");
		const engine = new DocumentationIntegrationEngine({
			outputDirectory,
			includeVisualizations: true,
		});

		const skillDocumentation = [
			{
				skillId: "hub",
				description: "Central hub skill",
				domain: "debug",
				dependencies: [],
				usageExamples: [],
				interactions: [
					{ withSkill: "peer-0", frequency: 2, successRate: 0.4 },
					{ withSkill: "peer-zero", frequency: 0, successRate: 0.4 },
					...Array.from({ length: 20 }, (_, index) => ({
						withSkill: `peer-${index + 1}`,
						frequency: 1,
						successRate: 0.95,
					})),
				],
			},
			...Array.from({ length: 22 }, (_, index) => ({
				skillId: `peer-${index}`,
				description: `Peer ${index}`,
				domain: index % 2 === 0 ? "debug" : "qual",
				dependencies: [],
				usageExamples: [],
				interactions: [],
			})),
			{
				skillId: "peer-zero",
				description: "Zero-frequency peer",
				domain: "qual",
				dependencies: [],
				usageExamples: [],
				interactions: [],
			},
		];

		await engine.generateArchitectureDocumentation(
			{
				agents: [{}],
				skills: [{ domain: "debug" }],
				routes: undefined,
				metrics: [],
			} as unknown as GraphVisualizationData,
			{
				agentTopology: undefined,
				bottlenecks: [],
				recommendations: [],
			} as unknown as GraphAnalysis,
			skillDocumentation,
		);

		const interactionDoc = readFileSync(
			join(outputDirectory, "SKILL_INTERACTIONS.md"),
			"utf8",
		);
		const dependencySvg = readFileSync(
			join(outputDirectory, "visuals", "skill-dependencies.svg"),
			"utf8",
		);
		const topologySvg = readFileSync(
			join(outputDirectory, "visuals", "agent-topology.svg"),
			"utf8",
		);

		expect(interactionDoc).toContain(
			"Showing the 20 busiest interaction edges",
		);
		expect(interactionDoc).toContain("Review hub ↔ peer-0");
		expect(interactionDoc).toContain(
			"Add caching or batching around highly connected skills",
		);
		expect(dependencySvg).toContain("unnamed-skill: no declared dependencies");
		expect(topologySvg).toContain("unnamed-agent (0 capabilities)");
	});

	it("generateSkillInteractionMaps renders empty-state summaries when no skills are supplied", async () => {
		const outputDirectory = makeTempDir("docs-empty-maps-");
		const engine = new DocumentationIntegrationEngine({
			outputDirectory,
			includePerformanceData: true,
		});

		await engine.generateSkillInteractionMaps([], []);

		const networkSvg = readFileSync(
			join(outputDirectory, "visuals", "skill-interaction-network.svg"),
			"utf8",
		);
		const dependencySvg = readFileSync(
			join(outputDirectory, "visuals", "skill-dependency-hierarchy.svg"),
			"utf8",
		);
		const domainSvg = readFileSync(
			join(outputDirectory, "visuals", "domain-interaction-map.svg"),
			"utf8",
		);
		const performanceSvg = readFileSync(
			join(outputDirectory, "visuals", "skill-performance-map.svg"),
			"utf8",
		);

		expect(networkSvg).toContain("No data available.");
		expect(dependencySvg).toContain("No data available.");
		expect(domainSvg).toContain("No data available.");
		expect(performanceSvg).toContain("No data available.");
	});
});
